default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: web_sistems__test_task
  password: password

development:
  <<: *default
  database: web_sistems__test_task_development

test:
  <<: *default
  database: web_sistems__test_task_test

production:
  <<: *default
  database: web_sistems__test_task_production
  username: web_sistems__test_task
  password: password
